version: '3.8'
services:

  firstservice-server:
    container_name: firstservice
    image: furkandemirturk/firstservice
    ports:
      - "8082:8082"
    networks:
      - spring-cloud-network
  
  adminservice-server:
    container_name: adminservice
    image: furkandemirturk/adminservice
    ports:
      - "8084:8084"
    networks:
      - spring-cloud-network

  springcloudgateway-server:
    container_name: springcloudgateway
    image: furkandemirturk/springcloudgateway
    ports:
      - "8081:8081"
    networks:
      - spring-cloud-network

networks:
    spring-cloud-network:
        driver: bridge
