name: spring-cloud-deployment

on:
  push:
    branches: 
      - master

jobs:
  adminservice:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
        working-directory: adminservice

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t adminservice .
          docker tag adminservice ${{ secrets.DOCKER_USERNAME }}/adminservice:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/adminservice:latest
          
  firstservice:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
        working-directory: firstservice

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t firstservice .
          docker tag firstservice ${{ secrets.DOCKER_USERNAME }}/firstservice:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/firstservice:latest

  springcloudgateway:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
        working-directory: springcloudgateway

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t springcloudgateway .
          docker tag springcloudgateway ${{ secrets.DOCKER_USERNAME }}/springcloudgateway:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/springcloudgateway:latest
    
