name: spring-cloud-deployment

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       include:
         - dockerfile: adminservice/Dockerfile
           image: "adminservice"
         - dockerfile: springcloudgateway/Dockerfile
           image: "springcloudgateway"
         - dockerfile: firstservice/Dockerfile
           image: "firstservice"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - uses: docker/build-push-action@v2
        with: 
          dockerfile: ${{ matrix.dockerfile }}
          context: .
          image: ${{ matrix.image }}
          
